"""Initial migration

Revision ID: 73423e95a024
Revises: 
Create Date: 2026-09-22 11:47:11.188151

"""
from alembic import op
import sqlalchemy as sa


revision = '73423e95a024'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('load_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern_name', sa.String(length=100), nullable=False),
    sa.Column('pattern_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'deleted', name='patternstatus'), nullable=False),
    sa.Column('expected_request_count', sa.Integer(), nullable=True),
    sa.Column('average_request_count', sa.Integer(), nullable=True),
    sa.Column('requests_per_second', sa.Integer(), nullable=True),
    sa.Column('peak_multiplier', sa.Float(), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('use_case', sa.String(length=200), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('base_cpu_cores', sa.Integer(), nullable=True),
    sa.Column('base_ram_gb', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_load_patterns_id'), 'load_patterns', ['id'], unique=False)
    op.create_table('pattern_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pattern_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_id'], ['load_patterns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pattern_likes_id'), 'pattern_likes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pattern_likes_id'), table_name='pattern_likes')
    op.drop_table('pattern_likes')
    op.drop_index(op.f('ix_load_patterns_id'), table_name='load_patterns')
    op.drop_table('load_patterns')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
